[project]
name = "diw-25-26"
version = "0.1.0"
description = "DIW 25-26"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.121.0",
    "psycopg2-binary>=2.9.11",
]
